Importing necessary libraries

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Loading the dataset

In [12]:
data = pd.read_csv('./data/KNN_Dataset.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Information about the data

In [11]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  121.675781      72.250000      26.447917  118.270833   
std       3.369578   30.436252      12.117203       9.733872   93.243829   
min       0.000000   44.000000      24.000000       7.000000   14.000000   
25%       1.000000   99.750000      64.000000      20.000000   79.000000   
50%       3.000000  117.000000      72.000000      23.000000   79.000000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    32.436589                  0.471876   33.240885    0.348958  
std      6.877335                  0.331329   11.760232    0.476951  
min     18.200000                  0.078000   21.000000    0.000000  
25%     27.500000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


Replacing zeros with the mean of the columns in the necessary columns as mentioned in the video from which i got the dataset
https://www.youtube.com/watch?v=4HKqjENq9OU

In [8]:
zeros_not_needed = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
for columns in zeros_not_needed:

    mean = int(data[columns].mean(skipna=True))
    data[columns] = data[columns].replace(0,mean)


Implementing KNN from scratch

In [17]:
X = (data.drop(columns = 'Outcome',inplace = False )).values
y = data['Outcome'].values
X_train = X[:600,:]
y_train = y[:600]
X_test = X[600:,:]
y_test = y[600:]

[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1
 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1
 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1
 0 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1
 1 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 

STEP 1 : Creating euclian distance function to create distance from the dataset points

In [21]:
def euclidean_distance(x1,x2):
    return np.sqrt(np.sum((x1-x2)**2))

In [22]:
def min_k_values(k,x1,x2):
    y = euclidean_distance(x1,x2)
    y_sorted = np.argsort(y)
    return y_sorted[:k-1]

In [ ]:
def count_outputs()

In [23]:
euclidean_distances = np.zeros([X_test.shape[0],X_train.shape[0]])
for i in range(X_test.shape[0]):
    for j in range(X_train.shape[0]):
        euclidean_distances[i][j] = euclidean_distance(X_test[i],X_train[j])

In [24]:
print(euclidean_distances)

[[ 53.43502156  34.09182308  81.7894491  ...  71.35485464  71.21929053
  130.08458805]
 [ 98.46421162  73.21499792 108.09899317 ...  41.25465017 108.17402832
  127.93125923]
 [ 32.24775541  40.4537143   70.36033815 ...  68.70378942  61.98387003
  127.60558079]
 ...
 [117.7833007  118.02190998 130.39398885 ... 104.94121495 126.38585621
   37.82375238]
 [ 43.58127217  53.16248681  59.87774486 ...  65.8204687   50.30862869
  126.43972226]
 [ 61.71982942  12.74524602  96.3199743  ...  53.96127812  87.42431886
  126.1399955 ]]


In [28]:
euclidean_distances_sorted_indexes = np.argsort(euclidean_distances,axis=1)
print(euclidean_distances_sorted_indexes)

[[249 200  66 ... 247 228  13]
 [430 533  15 ... 247 228  13]
 [ 23 386 321 ... 247 228  13]
 ...
 [384 477 217 ... 247 228  13]
 [264 246 523 ... 247 228  13]
 [262  96 253 ... 247 228  13]]


In [29]:
k = int(np.sqrt(X_train.shape[0]))
euclidean_distances_sorted_indexes_firstk = euclidean_distances_sorted_indexes[:,:k]

In [34]:
y_outputs = np.zeros([X_test.shape[0],k])
for i in range(X_test.shape[0]):
    y_outputs[i]= np.take_along_axis(y_train,euclidean_distances_sorted_indexes_firstk[i],axis=0)

print(y_outputs)

[[0. 0. 1. ... 0. 1. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 [1. 1. 1. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 1. 0. 1.]
 [1. 0. 1. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [35]:
print(y_outputs.shape)

(168, 24)


In [40]:
from collections import Counter

In [42]:
y_pred = np.zeros(X_test.shape[0])
for i in range(X_test.shape[0]):
    y_pred[i] = Counter(y_outputs[i]).most_common(1)[0][0]

print(y_pred)

[0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1.
 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0.]


In [43]:
y_pred.shape

(168,)

In [44]:
y_test

array([0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [45]:
correct_predictions = 0
for i in range(X_test.shape[0]):
    if y_test[i] == y_pred[i]:
        correct_predictions += 1

accuracy = correct_predictions / X_test.shape[0] * 100
print(accuracy)

73.21428571428571
